### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Jalle19** [kimmolinna/pycaruna#1]
Hi,

Can you add a LICENSE file to the repository? I'd like to fork this and use it but technically it's proprietary at the moment, since you haven't specified a license at all.

Thanks!

**Comment by Jalle19** [comment]
Ping

**Comment by Jalle19** [comment]
@kimmolinna ping

**Comment by kimmolinna** [comment]
Sorry I didn't notice your earlier message. I'll do it later today.

**Comment by Jalle19** [comment]
Awesome!

**Comment by kimmolinna** [comment]
@Jalle19 Now It's there. I hope MIT is okay for you.

**Comment by Jalle19** [comment]
That is perfect, thanks!
