### ISSUE TITLE
pycaruna stopped working after Caruna shut down their old service

### ISSUE THREAD

**Issue by masipila** [kimmolinna/pycaruna#8]
Hi,

pycaruna stopped working today after Caruna removed their good old Energiaseuranta section from their online service. The new Energiaseuranta is at the moment only displaying the consumption data in graph format only.

I just had a chat with Caruna customer service and they promised that their system should be updated with a new version "tomorrow or latest by the end of this week" which would contain the consumption data in numerical format (and as CSV).

Let's see what happens and how complex it will be to grab the consumption data from the new Energiaseuranta...

Cheers,
Markus

**Comment by kimmolinna** [comment]
I noticed the same thing. It's still possible to fetch json-files via API. I just have to change `energiaseuranta.caruna.fi` to `plus.caruna.fi` but the login protocol is a bit different. I try to do that in a couple of days.

**Comment by TimPox** [comment]
The new Energiaseuranta UI is a piece of crap compared to the old one.  Previous year is stuffed to the same graph etc. But anyways, fetching the json-data and using other means of handling the data is a solution to get over this.

**Comment by kimmolinna** [comment]
I managed to recreate a login procedure to `plus.caruna.fi`. Tomorrow I try to finalize next version. Then you should be able to fetch the json-data again. The format is a bit different but it includes temperature information too.

**Comment by TimPox** [comment]
Unfortunately this new Energiaseuranta sucks also otherwise than just the UI. Even when the yesterdays energy readings can be read and downloaded from Fingrid Datahub,  Energiaseuranta doesn't include that data (even when they have read the data and supplied it to Datahub), Their database system is somewhat buggy,

**Comment by kimmolinna** [comment]
I use [Entsoe](https://www.entsoe.eu/) for prices.

**Comment by masipila** [comment]
A bit off-topic from this issue, but I wonder how long Fingrid's portal keeps the session alive... 

It requires strong authentication but conceptually it would be possible to fetch data programmatically from there by having an initial setup phase where we grab the session ID one way or another (even manually via a web browser, since it's a one-time activity). And then pass the session ID as an input argument to the actual script that fetches the data. If (when) the Fingrid portal has a session timeout occurring after xyz, we could keep the session alive programmatically by making a dummy requests more frequently than that threshold with cron. Ugly kludge, but conceptually it should work...

I've been very happy with pycaruna so far. I've built this kind of a dashboard for keeping an eye on the "Kulutusvaikutus" that we have in our Väre Välkky contract (we pay 14.8 c/kWh +/- "kulutusvaikutus"). Our record so far is 14.8 c/kWh - 9.9 c/kWh this August when the prices were going wild...

Here's a screenshot of the dashboard: https://imgur.com/xVC24KC

**Comment by kimmolinna** [comment]
This issue is now fixed. Unfortunately It's only possible to fetch one day at the time but let's hope it's going to change in the future because you can fetch an excel file with time interval from aws bucket at the moment.

**Comment by kimmolinna** [comment]
@masipila It's quite simple by using [Entsoe](https://github.com/kimmolinna/entsoe/blob/main/pyentsoe.py).
You can find the instructions to get API KEY [from here](https://thesmartinsights.com/how-to-query-data-from-the-entso-e-transparency-platform-using-python/)

**Comment by masipila** [comment]
> This issue is now fixed. Unfortunately It's only possible to fetch one day at the time but let's hope it's going to change in the future because you can fetch an excel file with time interval from aws bucket at the moment.

Thank you so much Kimmo! I'll give it a spin this afternoon!

**Comment by masipila** [comment]
> @masipila It's quite simple by using [Entsoe](https://github.com/kimmolinna/entsoe/blob/main/pyentsoe.py). You can find the instructions to get API KEY [from here](https://thesmartinsights.com/how-to-query-data-from-the-entso-e-transparency-platform-using-python/)

I don't think Entsoe has the consumption data. I'm already fetching the spot prices from there, but my previous thinking out loud last night was about developing a similar consumption-fetcher from Fingrid Datahub that what this pycaruna is doing. See https://oma.datahub.fi/#/login The benefit of that is that it would work for everybody in Finland regardless who their power grid operator is.

But now that this pycaruna is updated, I personally don't need it because I live in Caruna network...

Cheers and thanks once more!
Markus

**Comment by kimmolinna** [comment]
@masipila Thanks for info. I didn't know about that service at all. I just know that Fingrid is using kdb+/KX Systems as their backend for data. :)

**Comment by masipila** [comment]
You're welcome :)

I submitted a feature request to Fingrid some weeks ago proposing that they would enable API access to consumers as follows:

1. Consumers can log in to https://oma.datahub.fi and generate an API token
2. Consumers can make an API request to fetch their own consumption data using the API token  

If somebody likes this idea, please send a feature request to Fingrid. I would assume the more folks request this, the more weight it gets in their backlog prioritization. Their feedback form can be found at https://support.datahub.fi/datahub?id=csm_public_form

I've noticed that the consumption data is available in Väre Välkky mobile app typically several hours before it's available in Caruna Energiaseuranta. Välkky fetches the data from Fingrid Datahub.

**Comment by kimmolinna** [comment]
@masipila It looks like I know which one is my next hobby project. ;)  At the moment the easiest way to work with Datahub api is to work exactly as you described earlier. Maybe it would be wise to use Selenium for getting an authorization token and then you could use it quite nicely.

**Comment by masipila** [comment]
When you have it ready for beta testing, please drop a line for example in this issue thread with a link to the new repo and I'll be more than glad to help with testing and smoothing the rough edges. 

Unfortunately all this frontend and beautifulsoup stuff is so much beyond my own comfort zone that I'm not able to help with the actual development...

Cheers,
Markus
